sources:
  GSFC:
    satellite: GSFC
    cycle_length: 9.9156
    window_size: 10
    window_padding: 2
    max_pass_number: 9999
  S6:
    satellite: S6
    cycle_length: 9.9156
    window_size: 10
    window_padding: 2
    max_pass_number: 9999
