sources:
  GSFC:
    satellite: GSFC
    filename_template: "{satellite}-SSH_alt_ref_at_v1_{date}.nc"
    s3_prefix: "daily_files/p1"
    source_mss: DTU15
    target_mss: DTU21
    mss_diff_file: DTU15_minus_DTU21.nc
    empty_template: gsfc_empty_template.nc
    smoothing:
      speed: 5.745
      sigma: 15
    collections:
      - shortname: MERGED_TP_J1_OSTM_OST_CYCLES_V52
        concept_id: C2901523432-POCLOUD
        source_label: "Integrated Multi-Mission Ocean Altimeter Data for Climate Research Version 5.2"
        source_url: "https://podaac.jpl.nasa.gov/dataset/MERGED_TP_J1_OSTM_OST_CYCLES_V52"
        reference: "https://doi.org/10.5067/ALTUG-TJ152"
  S6:
    satellite: S6
    filename_template: "{satellite}-SSH_alt_ref_at_v1_{date}.nc"
    s3_prefix: "daily_files/p1"
    source_mss: DTU18
    target_mss: DTU21
    mss_diff_file: DTU18_minus_DTU21.nc
    empty_template: s6_empty_template.nc
    smoothing:
      speed: 5.745
      sigma: 15
    collections:
      - shortname: JASON_CS_S6A_L2_ALT_LR_RED_OST_NTC_G01
        concept_id: C3332203845-POCLOUD
        priority: 1
        source_label: "Sentinel-6A MF Jason-CS L2 P4 Altimeter Low Resolution (LR) NTC Reduced Ocean Surface Topography G01"
        source_url: "https://podaac.jpl.nasa.gov/dataset/JASON_CS_S6A_L2_ALT_LR_RED_OST_NTC_G01"
        reference: "https://doi.org/10.5067/S6AP4-2LRNTR-G01"
      - shortname: JASON_CS_S6A_L2_ALT_LR_RED_OST_NTC_G01_UNVALIDATED
        concept_id: C3332203819-POCLOUD
        priority: 2
        source_label: "Sentinel-6A MF Jason-CS L2 P4 Altimeter Low Resolution (LR) NTC Reduced Ocean Surface Topography (Unvalidated) G01"
        source_url: "https://podaac.jpl.nasa.gov/dataset/JASON_CS_S6A_L2_ALT_LR_RED_OST_NTC_G01_UNVALIDATED"
        reference: "https://doi.org/10.5067/S6AP4-2LRNUR-G01"
      - shortname: JASON_CS_S6A_L2_ALT_LR_RED_OST_STC_F
        concept_id: C1968979561-POCLOUD
        priority: 3
        source_label: "Sentinel-6A MF Jason-CS L2 P4 Altimeter Low Resolution (LR) STC Reduced Ocean Surface Topography"
        source_url: "https://podaac.jpl.nasa.gov/dataset/JASON_CS_S6A_L2_ALT_LR_RED_OST_STC_F"
        reference: "https://doi.org/10.5067/S6AP4-2LRST"
  S6B:
    satellite: S6B
    filename_template: "{satellite}-SSH_alt_ref_at_v1_{date}.nc"
    s3_prefix: "daily_files/p1"
    source_mss: DTU18
    target_mss: DTU21
    mss_diff_file: DTU18_minus_DTU21.nc
    empty_template: s6b_empty_template.nc
    smoothing:
      speed: 5.745
      sigma: 15
    collections:
      - shortname: JASON_CS_S6B_L2_ALT_LR_RED_OST_STC_G
        concept_id: C3213767230-POCLOUD
        priority: 1
        source_label: "Sentinel-6B/Jason-CS L2 P4 Altimeter Low Resolution (LR) STC Reduced Ocean Surface Topography"
        source_url: "https://podaac.jpl.nasa.gov/dataset/JASON_CS_S6B_L2_ALT_LR_RED_OST_STC_G"
        reference: "https://doi.org/10.5067/S6BP4-2LRST"
